version: '3.8'

services:
  chinese_db:
    image: postgres:15
    container_name: chinese_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: chinese_db
    ports:
      - "5432:5432"
    volumes:
      - chinese_data:/var/lib/postgresql/data

  backend:
    build: ../../../../../..
    ports:
      - "8080:8080"
    depends_on:
      - chinese_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://chinese_db:5432/chinese_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123

volumes:
  chinese_data:
